'use client'

import Navigation from '@/components/navigation'
import Footer from '@/components/footer'
import { useState } from 'react'
import { ChevronDown } from 'lucide-react'

export default function FAQPage() {
  const [openIndex, setOpenIndex] = useState<number | null>(0)

  const faqs = [
    {
      question: 'How accurate are the captions generated by DVisionAI?',
      answer: 'DVisionAI uses advanced AI models trained on millions of images, achieving 99.8% accuracy in most scenarios. The accuracy depends on image quality and complexity.',
    },
    {
      question: 'What image formats are supported?',
      answer: 'We support all common image formats including JPEG, PNG, WebP, GIF, BMP, and TIFF. Maximum file size is 50MB.',
    },
    {
      question: 'Is my data stored or shared?',
      answer: 'No, we prioritize your privacy. Images are processed in real-time and never stored on our servers. We never share your data with third parties.',
    },
    {
      question: 'How fast is the processing?',
      answer: 'Most images are processed in under 500ms. Processing speed depends on image complexity and current server load.',
    },
    {
      question: 'Can I use DVisionAI for commercial purposes?',
      answer: 'Yes, all paid plans allow commercial use. Please review our terms of service for specific details.',
    },
    {
      question: 'Is there an API available?',
      answer: 'Yes, our Pro and Enterprise plans include API access. Check our documentation for integration details.',
    },
    {
      question: 'What languages are supported?',
      answer: 'Captions can be generated in 150+ languages. Select your preferred language in the app settings.',
    },
    {
      question: 'Can I cancel my subscription anytime?',
      answer: 'Yes, you can cancel your subscription at any time with no penalties or long-term commitments.',
    },
  ]

  return (
    <main className="min-h-screen bg-background text-foreground">
      <Navigation />

      <section className="pt-32 pb-24">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto">
            <div className="text-center mb-16">
              <h1 className="text-5xl md:text-6xl font-bold mb-6 gradient-text">Frequently Asked Questions</h1>
              <p className="text-xl text-muted-foreground">Find answers to common questions about DVisionAI.</p>
            </div>

            <div className="space-y-4">
              {faqs.map((faq, i) => (
                <button
                  key={i}
                  onClick={() => setOpenIndex(openIndex === i ? null : i)}
                  className="w-full glass-dark p-6 text-left transition-all hover:bg-opacity-50"
                >
                  <div className="flex items-center justify-between">
                    <h3 className="text-lg font-semibold pr-4">{faq.question}</h3>
                    <ChevronDown
                      size={20}
                      className={`flex-shrink-0 transition-transform ${
                        openIndex === i ? 'rotate-180' : ''
                      }`}
                    />
                  </div>

                  {openIndex === i && (
                    <p className="mt-4 text-muted-foreground">{faq.answer}</p>
                  )}
                </button>
              ))}
            </div>

            <div className="mt-16 glass-dark p-8 text-center">
              <h2 className="text-2xl font-bold mb-4">Still have questions?</h2>
              <p className="text-muted-foreground mb-6">Can't find the answer you're looking for? Our team is here to help.</p>
              <button className="px-8 py-3 bg-primary hover:bg-primary/90 text-primary-foreground rounded-lg font-semibold transition-all">
                Contact Support
              </button>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  )
}
